export const GET_CONVERSIONS_REQUESTED = 'GET_CONVERSIONS_REQUESTED';
export const GET_CONVERSIONS_SUCCESS = 'GET_CONVERSIONS_SUCCESS';
export const GET_CONVERSIONS_FAILED = 'GET_CONVERSIONS_FAILED';
export const GET_CONVERSION_HISTORY_REQUESTED =
  'GET_CONVERSION_HISTORY_REQUESTED';
export const GET_CONVERSION_HISTORY_SUCCESS = 'GET_CONVERSION_HISTORY_SUCCESS';
export const GET_CONVERSION_HISTORY_FAILED = 'GET_CONVERSION_HISTORY_FAILED';
