export const GET_CONVERSIONS_REQUESTED = 'GET_CONVERSIONS_REQUESTED';
export const GET_CONVERSIONS_SUCCESS = 'GET_CONVERSIONS_SUCCESS';
export const GET_CONVERSIONS_FAILED = 'GET_CONVERSIONS_FAILED';
